---
title: "Data Cleaning"
output: html_document
---

Description: This document contains our data cleaning and processing steps.

```{r}
# Data cleaning steps

# Gender will be recode into: male = 0, female = 1

# Age band will be recode into ordinal numeric levels

# all drug use will be recode into numbers below
# 0: never used
# 1: Used over a Decade Ago
# 2: Used in Last Decade
# 3: Used in Last Year
# 4: Used in Last Month
# 5: Used in Last Week
# 6: Used in Last Day

# Since we are not using education, country, and ethnicity, these valuable are unchanged

```

```{r}
# Load in necessary libraries
library(tidyverse)

# Load raw dataset
# Starting number of rows is 1884 and columns is 32
raw = read_csv("data/Drug_Consumption.csv")

# Recode gender
cleaned = raw |>
  mutate(Gender = if_else(Gender == "M", 0,
                          if_else(Gender == "F", 1, NA_real_)),
         Gender = as.factor(Gender))

# Recode age bands → ordinal numeric levels
age_levels = c(
  "18-24" = 1,
  "25-34" = 2,
  "35-44" = 3,
  "45-54" = 4,
  "55-64" = 5,
  "65+"   = 6
)

cleaned <- cleaned |>
  mutate(Age = age_levels[Age] |> as.numeric())

# Identify drug-use variables (all columns that start with CL-values)
drug_vars = names(raw)[sapply(raw, function(x) any(grepl("^CL[0-6]", x)))]

# Remove "CL" prefix from all drug-use variables and convert to numeric
cleaned <- cleaned |>
  mutate(across(all_of(drug_vars),
                ~ str_remove(.x, "CL") |> as.numeric()))

# Rename "AScore" column to "Ascore" to match the names of the other OCEAN columns
cleaned = cleaned |>
  dplyr::rename(Ascore = AScore)

# Remove individuals who responded with anything other than 0 (never used) to the fictitious drug (Semeron) which was introduced to identify over-claimers and then remove the Semer column
# Now the number of rows is 1876 and columns is 31
cleaned = cleaned |>
  filter(Semer == 0) |> 
  select(-Semer)

# Save cleaned dataset
write_csv(cleaned, "data/cleaned_drug_data.csv")

```



