---
title: "eda"
output: github_document
---


```{r}
# Load in relevant libraries
library(tidyverse)
library(patchwork)

# default options
knitr::opts_chunk$set(
  fig.width = 6,
  fig.asp = .6,
  out.width = "90%"
)

theme_set(theme_minimal() + theme(legend.position = "bottom"))

options(
  ggplot2.continuous.colour = "viridis",
  ggplot2.continuous.fill = "viridis"
)

scale_colour_discrete = scale_colour_viridis_d
scale_fill_discrete = scale_fill_viridis_d

```


```{r}
# Read in cleaned dataset
drug_data = read_csv("data/cleaned_drug_data.csv") |>
  mutate(
    Gender = as.factor(Gender))

# Create version of the dataset where we collapse drug levels across all drug use columns into a binary user vs. non-user indicator "user_status"
# 0-1: non-user
# 2–6: user
usage_data = drug_data |>
  mutate(across(14:31, ~ factor(ifelse(.x %in% 0:1, "non-user",
                         ifelse(.x %in% 2:6, "user", NA)),
                        levels = c("non-user", "user"))),
         # define user as those who have used any drug in the past decade excluding chocolate and caffeine
         user_status = factor(if_else(rowSums(across(c(14:31, -18, -20)) == "user", na.rm = TRUE) > 0, 
                                          "user", "non-user"),
                          levels = c("non-user", "user")))

# Gender
# 0: male
# 1: female

# Drug use
# 0: never used
# 1: used over a Decade Ago
# 2: used in Last Decade
# 3: used in Last Year
# 4: used in Last Month
# 5: used in Last Week
# 6: used in Last Day

# Age
# 1: 18-24
# 2: 25-34
# 3: 35-44
# 4: 45-54
# 5: 55-64
# 6: 65+

```


# Trait distributions

Histogram of OCEAN Scores
```{r}
O_hist = drug_data |> 
  ggplot(aes(x = Oscore)) + 
  geom_histogram(fill = "#F4C2C2", color = "white", binwidth = 0.4) +
  labs(
    x = "Openness to Experience (O)",
    y = "Count"
  ) 
C_hist = drug_data |> 
  ggplot(aes(x = Cscore)) + 
  geom_histogram(fill = "#FFB6C1", color = "white", binwidth = 0.4) +
  labs(
    x = "Conscientiousness (C)",
    y = "Count"
  ) 

E_hist = drug_data |> 
  ggplot(aes(x = Escore)) + 
  geom_histogram(fill = "#FFA6C9", color = "white", binwidth = 0.4) +
  labs(
    x = "Extraversion (E)",
    y = "Count"
  ) 

A_hist = drug_data |> 
  ggplot(aes(x = Ascore)) + 
  geom_histogram(fill = "#FF1493", color = "white", binwidth = 0.4) +
  labs(
    x = "Agreeableness (A)",
    y = "Count"
  ) 

N_hist = drug_data |> 
  ggplot(aes(x = Nscore)) + 
  geom_histogram(fill = "#F9429E", color = "white", binwidth = 0.4) +
  labs(
    x = "Neuroticism (N)",
    y = "Count"
  ) 

OCEAN_hist = (O_hist + C_hist + E_hist) / (A_hist + N_hist) + 
  plot_annotation(
    title = "Distribution of OCEAN Scores"
  )

OCEAN_hist
ggsave("figs/hist_ocean.png", OCEAN_hist)

```

Histogram of impulsivity
```{r}
impulsivity_hist = drug_data |> 
  ggplot(aes(x = Impulsive)) + 
  geom_histogram(fill = "#FFE4E1", color = "white", binwidth = 0.4) +
  labs(
    x = "Impulsivity",
    y = "Count",
    title = "Distribution of Impulsivity Scores"
  ) 

impulsivity_hist
ggsave("figs/hist_impulsivity.png", impulsivity_hist)

```

Histogram of sensation seeking
```{r}
SS_hist = drug_data |> 
  ggplot(aes(x = SS)) + 
  geom_histogram(fill = "#FFB7C5", color = "white", binwidth = 0.3) +
  labs(
    x = "Sensation Seeking (SS)",
    y = "Count",
    title = "Distribution of SS Scores"
  ) 

SS_hist
ggsave("figs/hist_impSS.png", SS_hist)

```


# Traits by User Status

Boxplot of OCEAN by user status
```{r}
OCEAN_boxplot = usage_data |> 
  pivot_longer(
    Nscore:Cscore,
    names_to = "OCEAN", 
    values_to = "Score") |> 
  mutate(OCEAN = fct_relevel(OCEAN, c("Oscore", "Cscore", "Escore", "Ascore", "Nscore"))) |>
  ggplot(aes(x = OCEAN, y = Score, fill = user_status)) + 
  geom_boxplot() +
  labs(
    x = "OCEAN",
    y = "Scores",
    fill = "Drug User Status",
    title = "Boxplot of OCEAN by User Status",
    caption = "Note: Drug user defined as those who have used any drug in the past decade excluding caffeine and chocolate."
  ) +
  scale_fill_manual(values = c("non-user" = "#D8BFD8", "user" = "#DA70D6")) +
  scale_x_discrete(labels = c("Openness to Experience (O)", "Conscientiousness (C)", "Extraversion (E)",
                              "Agreeableness (A)", "Neuroticism (N)")) +
  theme(axis.text.x = element_text(angle = 45, hjust = 1))

OCEAN_boxplot
ggsave("figs/box_ocean_user.png", OCEAN_boxplot)

```

Boxplot of impulsivity by user status
```{r}
impulsivity_boxplot = usage_data |> 
  ggplot(aes(x = user_status, y = Impulsive)) + 
  geom_boxplot() +
  labs(
    x = "Drug User Status",
    y = "Impulsivity Scores",
    title = "Boxplot of Impulsivity by User Status",
    caption = "Note: Drug user defined as those who have used any drug in the past decade excluding caffeine and chocolate."
  ) +
  scale_fill_manual(values = c("non-user" = "#9400D3", "user" = "#BA55D3")) +
  theme(axis.text.x = element_text(angle = 45, hjust = 1))

impulsivity_boxplot
ggsave("figs/box_ocean_user.png", OCEAN_boxplot)

```


# Legal vs Illegal Usage

Stacked barplot of legal vs illegal usage
```{r}

```

Heatmap of correlations
```{r}

```








